### ISSUE TITLE
Rocksmith Realtone Cable/ MIDI support

### ISSUE THREAD

**Issue by 8bitguitarlord** [YARC-Official/YARG#168]
This lets the player use a real guitar to play like the Rock Band 3 pro guitar highway with a interphase system.

**Comment by ieee802dot11ac** [comment]
The way RockSmith's Realtone cables work is wholly different from the way Rock Band guitars work (something something audio parsing vs. just getting the held frets), so it won't work.

**Comment by farsdewibs0n** [comment]
Rocksmith realtone cable works as just like an input device (like microphone).
Iirc the RB3 Pro Guitar works as a MIDI device (the whole fret is basically a button). 

Unless you own a midi guitar (example: Casio DG-20 or RB3 Pro Guitar) pro guitar can't really work.
Converting he tone to midi real time is out of question because how imprecise the guitar cam be and converting can add latency.

However I support the idea of adding MIDI support for pro keys.

**Comment by RileyTheFox** [comment]
Late response but most likely will never happen. Many people have suggested this but it would be far too difficult to get working correctly
