### ISSUE TITLE
Yard Android Version - Progress so far 

### ISSUE THREAD

**Issue by ebellumat** [YARC-Official/YARG#506]
This is Yarg running via Bluestacks. I had to nerf lots of routines that deals with Folder scaning, folders creation and sorting, but after 2 days of hard work, recreating the install.py for Android, changing plugins archtectures, it's working! Now i have to create the touch screen input and that's it, we are ready to go! 

https://github.com/YARC-Official/YARG/assets/26942680/8fe25298-ca7a-47de-bb5c-9f60bdd81a3e

**Comment by ebellumat** [comment]
I just don't know why this song are usign the purple bar to the hammer on instead the small square, i have to investigate.

**Comment by TheNathannator** [comment]
I think you might wanna post progress updates like this in our Discord server instead of using the issue tracker lol, that's not what it's for. Very cool to see regardless though!

> I just don't know why this song are usign the purple bar to the hammer on instead the small square

This most likely isn't any sort of issue, that's just a decision the charter made when charting the song.

Also, regarding issues with file/directory access, you may need to give the game file system permissions instead of just nuking all of the file operations, as those are pretty important for everything to work correctly.

**Comment by ebellumat** [comment]
Yeah, closing this one! Thank you for the help so far! I mean, i made some changes that i think can be uses on the main source code, like virtual drives and this kinda of suff! We can check out later. But for now i'm thinking in how to translate the touch for the controllers. Invisible buttons maybe? And i also need a auto picking system... Not easy to accomplish.
