### ISSUE TITLE
Guitars seemingly loses score multiplier when transitioning to other frets

### ISSUE THREAD

**Issue by ClampyStew** [YARC-Official/YARG#602]
Sorry for the lossy video. I had to use a google drive link for this
[Video](https://drive.google.com/file/d/1r1YEzNGUSxQGl2sqeHnhZNpaKpDdmYwo/view?usp=sharing)

**HOW TO REPLICATE**
1) Obtain The Black Parade, and the charts from WoR
2) Play on Nightly build 15dd0cc
3) Set up bot for 5-lanes Guitar
The bot should seemingly lose the score multiplier every time it tries to switch frets

**Comment by ClampyStew** [comment]
It also does not seems to be consistent in the error as well

**Comment by TheNathannator** [comment]
The issue visible here should largely be fixed, however the actual problem that causes it is not.

There's an engine quirk that happens with sustains that go right up to the next note, which causes the bot to overstrum when switching frets. Sustain scoring avoids this issue in most cases with the feature that auto-finishes sustains once you get close enough to their end, but it's likely still possible in some cases.

For now I'm gonna close this issue to reduce issue count, since the majority case is fixed.
