### ISSUE TITLE
Problems installing YARG on Linux

### ISSUE THREAD

**Issue by ElGabol0te** [YARC-Official/YARG#665]
So I was installing YARG on my computer, and everything was normal until I opened the .AppImage file on my terminal

![Screenshot 2024-02-05 9 27 52 PM](https://github.com/YARC-Official/YARG/assets/159105721/e585aec8-22d4-4b3c-8424-e4c91a8dc937)

I don't know what happened, I tried to search the file in GitHub, but I didn't find anything

I'm nearly new to Linux so I don't know very much about this

My computer is a Chromebook with Linux Debian 11

**Comment by TheNathannator** [comment]
This isn't an issue on the game's end, `libOpenGL` is a system-provided library which Unity (and a whole bunch of other software) depends on for rendering to the screen. I don't think the game will run on Chromebook unless you can find OpenGL drivers for it.

Closing this since there's nothing we can do on our end for this.

**Comment by ElGabol0te** [comment]
Thanks for the help!, I will try to search for drivers or something, or maybe I should try Wine and install the .exe and run it
