### ISSUE TITLE
Font issues with lyric text (missing glyphs)

### ISSUE THREAD

**Issue by rk-exxec** [YARC-Official/YARG#760]
Hey, me again with another font issue on the dev branch.

I found that the font used in the lyric bar has the extended ascii glyphs missing (such as öäü).
I also noticed, that its font atlas is set to static. (Red Hat Display Bold)
While other RHD weights have a dynamic atlas enabled.

What would be the best course of action here? 
Add the missing glyphs to the font atlas or set it to dynamic?

Also, the Barlow font has a mix of static and dynamic as well.
NotoSans is purely Dynamic.

Should these be unified or is there a performance / memory concern here?

**Comment by EliteAsian123** [comment]
Dynamic fonts have the problem of increasing the build size by a very significant amount (and due to GitHub's size limits, we gotta keep the sizes below 2GB). 

Which reminds me, here are the build sizes before the addition of NotoSans:
![image](https://github.com/YARC-Official/YARG/assets/29520859/c9e17366-1242-49fc-ad08-54f3e09fb384)
And here is after:
![image](https://github.com/YARC-Official/YARG/assets/29520859/ea67100c-271d-4795-b091-beee8b2374a8)

So yeah, quite a significant increase after those additions.

Because of this, I am going to say the best course of action is to:
* Set all main fonts to use static atlases. We should, however, use a slightly wider range of characters to allow them to display. We obviously can't have *all* characters, as then that would defeat the purpose, but as said a slightly wider range should be enough.
* NotoSans should be kept dynamic. Backup fonts will be slower on the system, but since they are backup fonts they are less likely to be seen. Because of this, however, we should also reduce the amount of variations of NotoSans we are using. Using Regular along with Regular Italic should be enough (or a thinner variant, whatever is more suitable for the general use case). This should reduce the build size while allowing more characters to be available.
