### ISSUE TITLE
First note when loading into a track has Infinite Front End.

### ISSUE THREAD

**Issue by doboggio** [YARC-Official/YARG#832]
Any song/section (whether you're in Quickplay or Practice) that starts with a Tap/HOPO can be hit using the Infinite Front End, regardless if it's disabled. 

How to replicate:

Find a song that either starts with a tap note, or has a section that starts with a tap or HOPO note
Load song in either Quickplay or Practice
Hold down note
The note will hit

Example Chart this works for: https://enchor.us/?hash=e91fd707f131875d98581390789d3003

**Comment by RileyTheFox** [comment]
Forgot to reply to this but this is intentional. Its a quality of life feature to make starting sections with hopos/taps in practice mode particularly much less annoying to deal with if the first note is an anchor note.

It could be disabled in QuickPlay but currently the engine has no awareness of QuickPlay vs Practice. Going to close this as I don't have any intention to change this behaviour for the foreseeable future
