### ISSUE TITLE
Wii Harmonix guitar not binding buttons

### ISSUE THREAD

**Issue by revenador** [YARC-Official/YARG#904]
Trying to set up the Wii Harmonix guitar (with the original usb dongle) on Linux. 
Cant bind green button and strum. Seemingly just doesn't register the button presses.

Have tried both stable and nightly builds.

I have confirmed the inputs are working with jstest and everything works fine on clone hero so I'm fairly sure it's not a hardware
issue.

Revenador

**Comment by TheNathannator** [comment]
Make sure you've followed the Linux setup instruction in the readme to install `hidapi` and `libudev`: https://github.com/YARC-Official/YARG?tab=readme-ov-file#linux

YARG doesn't yet have proper support for the standard `evdev` input subsystem on Linux, so some setup is required currently. Once that's implemented, things should work more smoothly.

**Comment by revenador** [comment]
Thanks for the quick reply. 
So sorry to have wasted your time. 
I had done the stuff in the readme but I thought I had tested the nightly build and apparently I hadn't. 
It's auto-detected and works fine on the current nightly build. 
(about 80% of the buttons worked on stable and it didn't auto fill the key bindings)

**Comment by TheNathannator** [comment]
That's the one part I forgot to mention lol, some fixes were introduced recently in the nightly version for the HID backend, so things work there. Probably would be good to release one more v0.12 version with those fixes applied so people don't have to rely on nightly.

Glad you have it working now!

**Comment by appsforartists** [comment]
I'm having this same issue on NixOS.  It looks like the correct modules are included in the package:

https://github.com/NixOS/nixpkgs/blob/nixos-24.11/pkgs/by-name/ya/yarg/package.nix#L120

When I start YARG, there's a toast that says 5 devices found and then a flurry of _Device removed_ ones for my WII peripherals:

- Licensed by Nintendo of America Harmonix Drum Controller for Nintendo Wii
- Harmonix Guitar Controller for Nintendo Wii
- HHD Shortcuts (Legion Mode: FPS)

It then says something about a MIDI device being added.  I don't own any MIDI devices, so I have no idea what that is.

I tried adding this to my Nix config, but it doesn't seem to have helped:
```nix
    services.udev.packages = lib.singleton (
      pkgs.writeTextFile {
        name = "yarg-udev-rules";
        text = ''
          KERNEL=="hidraw*", TAG+="uaccess"
        '';
        destination = "/etc/udev/rules.d/69-yarg-hid.rules";
      }
    );
```

When I first started the game, I noticed I was getting bizarre buttons (like trigger).  While I was trying to debug this, I turned off Steam Input.  I suspect that's why I originally was able to map some buttons on the guitar (but never anything on the drums).  

Maybe next I'll try making a Steam Input profile to see if I can work around this problem by mapping the controller to an Xbox one and then mapping it again in YARG bindings.
